name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: smart  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose services
        run: |
          docker compose build

      - name: Push Docker images
        run: |
          docker compose push

      - name: Verify images
        run: |
          docker images
